### ISSUE TITLE
Menu item overflows on really long text.

### ISSUE THREAD

**Issue by sebastienlabine** [vechai/vechaiui#5]
When a menu item is really long, the text overflows due to the fact that the height is pre-defined.
```css 
h-8 {
  height: 2rem;
}
![image](https://user-images.githubusercontent.com/8888846/124614036-da33cb00-de41-11eb-9805-670192d32862.png)

````
**Suggestion**
Change the height to min-height. However this may have effect on other properties.
```css 
h-8 {
  min-height: 2rem;
}
````
![image](https://user-images.githubusercontent.com/8888846/124614407-30087300-de42-11eb-957a-c09d051b8243.png)
